version: "3.4"

services:
  api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:api"
    ports:
      #- "${PORT}:${PORT}"
      # DK Added
      - 80:3080
    depends_on:
      - mongodb
      - rag_api
    restart: always
    user: "${UID}:${GID}"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=${RAG_PORT:-8000}
      - RAG_API_URL=http://rag_api:${RAG_PORT:-8000}
  mongodb:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:mongodb"
    restart: always
    user: "${UID}:${GID}"
    command: mongod --noauth
  meilisearch:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:meilisearch"
    restart: always
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
  vectordb:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:vectordb"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
  rag_api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:rag_api"
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=${RAG_PORT:-8000}
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
  actions:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:actions"
    # linux/amd64 for Silicon Mac
    platform: linux/amd64
    ports:
      # API
      - 3001:8080
      # Action server portal
      - 4001:8087

volumes:
  pgdata2: