#version: "3.4"

services:
  server:
     platform: linux/amd64
     container_name: recipes-ai-server
     build:
       context: .
       dockerfile: ./server/fastapi/Dockerfile
       args:
         DATA_DB_CONN_STRING: ${DATA_DB_CONN_STRING}
     env_file:
       - .env
     volumes:
       - shared-data:/app/recipes/public
  chat:
     platform: linux/amd64
     container_name: recipes-ai-chat
     build:
       context: .
       dockerfile: ./ui/chat-chainlit-assistant/Dockerfile
     ports:
       - 80:8000
     env_file:
       - .env
     volumes:
       - shared-data:/app/public/images

volumes:
  pgdata2:
  shared-data: