version: "3.4"

services:
  api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:api"
    platform: "linux/amd64"
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - rag_api
    restart: always
    user: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb://mongodb:27017/LibreChat
      MEILI_HOST: http://meilisearch:7700
      RAG_PORT: 8000
      RAG_API_URL: http://rag_api:8000
  mongodb:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:mongodb"
    platform: "linux/amd64"
    restart: always
    user: "${UID}:${GID}"
    command: mongod --noauth
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data/mongodb:/data/db
  meilisearch:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:meilisearch"
    #platform: "linux/amd64"
    restart: always
    user: "${UID}:${GID}"
    environment:
      MEILI_HOST: http://meilisearch:7700
      MEILI_NO_ANALYTICS: true
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data/meili_data:/meili_data
  vectordb:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:vectordb"
    platform: "linux/amd64"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    restart: always
    volumes:
      - ${WEBAPP_STORAGE_HOME}/data/vectordb:/var/lib/postgresql/data
  rag_api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:rag_api"
    platform: "linux/amd64"
    environment:
      DB_HOST: vectordb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      RAG_PORT: 8000
    restart: always
    depends_on:
      - vectordb
  actions:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:actions"
    platform: linux/amd64

volumes:
  pgdata2: