services:
  promptflow:
    build:
      context: .
      dockerfile: ./flows/chainlit-ui-evaluation/Dockerfile
      args:
        OPENAI_API_KEY: ${ASSISTANTS_API_KEY}
        OPENAI_API_ENDPOINT: ${ASSISTANTS_BASE_URL}
        OPENAI_API_VERSION: ${ASSISTANTS_API_VERSION}
    container_name: recipes-ai-promptflow
    env_file:
      - .env
    volumes:
      - ./flows:/app
      - ./utils:/app/chainlit-ui-evaluation/utils
      - ./templates:/app/chainlit-ui-evaluation/templates
      - shared-data:/app/chainlit-ui-evaluation/recipes/public
      - ./management/skills.py:/app/chainlit-ui-evaluation/recipes/skills.py
      - ./ui/chat-chainlit-assistant/app.py:/app/chainlit-ui-evaluation/app.py
