version: "3.4"

services:
  api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:api"
    platform: "linux/amd64"
    ports:
      - "80:80"
    depends_on:
      - mongodb
      - rag_api
    restart: always
    user: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb+srv://matthew:c5tZja0psz5Qo7dC@hum-ai-libre-chat.mcyk70v.mongodb.net/?retryWrites=true&w=majority&appName=hum-ai-libre-chat
      MEILI_HOST: http://meilisearch:7700
      RAG_PORT: 8000
      RAG_API_URL: http://rag_api:8000
  meilisearch:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:meilisearch"
    #platform: "linux/amd64"
    restart: always
    user: "${UID}:${GID}"
    environment:
      MEILI_HOST: http://meilisearch:7700
      MEILI_NO_ANALYTICS: true
  #vectordb:
  #  image: "dkdsprototypesreg01.azurecr.io/containergroup:vectordb"
  #  platform: "linux/amd64"
  #  environment:
  #    POSTGRES_DB: mydatabase
  #    POSTGRES_USER: myuser
  #    POSTGRES_PASSWORD: mypassword
  #  restart: always
  rag_api:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:rag_api"
    platform: "linux/amd64"
    environment:
      DB: hdexpert-alpha
      DB_PORT: 5432
      DB_HOST: postgres-prototypes.postgres.database.azure.com
      POSTGRES_USER: bots_rule3
      POSTGRES_PASSWORD: 96__Mou9!2Yl
      RAG_PORT: 8000
    restart: always
  actions:
    image: "dkdsprototypesreg01.azurecr.io/containergroup:actions"
    platform: linux/amd64
    volumes:
      - shared-data:/action-server/actions/actions_plugins/recipe-server/images
  init:
    image: dkdsprototypesreg01.azurecr.io/containergroup:init
    volumes:
      - shared-data:/data
    command: "sh -c 'chown -R 1000:1000 /data && chmod -R 775 /data'"
    user: "root"
    depends_on:
      - actions
  nginx:
    image: dkdsprototypesreg01.azurecr.io/containergroup:nginx
    volumes:
      - shared-data:/usr/share/nginx/html
    restart: always
  code-interpretor:
    image: dkdsprototypesreg01.azurecr.io/containergroup:code-interpreter
    volumes:
      - ./code-interpretor/static:/app/static
    command: python3 -c "import localserver.main; localserver.main.start()"

volumes:
  shared-data: