version: "3.4"

services:
  api:
    image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:api"
    platform: "linux/amd64"
    ports:
      - "80:80"
    depends_on:
      #- mongodb
      - rag_api
    restart: always
    user: ""
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HOST: 0.0.0.0
      MONGO_URI: mongodb+srv://matthew:c5tZja0psz5Qo7dC@hum-ai-libre-chat.mcyk70v.mongodb.net/?retryWrites=true&w=majority&appName=hum-ai-libre-chat
      MEILI_HOST: http://meilisearch:7700
      RAG_PORT: 8000
      RAG_API_URL: http://rag_api:8000
  meilisearch:
    image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:meilisearch"
    #platform: "linux/amd64"
    restart: always
    user: "${UID}:${GID}"
    environment:
      MEILI_HOST: http://meilisearch:7700
      MEILI_NO_ANALYTICS: true
  rag_api:
    image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:rag_api"
    platform: "linux/amd64"
    environment:
      DB_HOST: docsdb
      POSTGRES_DB: docs
      POSTGRES_USER: ${POSTGRES_DATA_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_PASSWORD}
      RAG_PORT: ${RAG_PORT:-8000}
      RAG_AZURE_OPENAI_API_KEY: ${AZURE_API_KEY_ENV}
      EMBEDDINGS_PROVIDER: azure
      EMBEDDINGS_MODEL: text-embedding-ada-002
      AZURE_OPENAI_ENDPOINT: https://dkopenai2.openai.azure.com/
      DEBUG_RAG_API: "True"
    restart: always
  docsdb:
    platform: linux/amd64
    image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:docsdb"
    environment:
      POSTGRES_DB: docs
      POSTGRES_USER: ${POSTGRES_DATA_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DATA_PASSWORD}
    restart: always
    #ports:
    #  - 5434:5432
  #  #volumes:
  #  #  - ./ui/recipes_assistant_chat/docsdb:/var/lib/postgresql/data
    env_file:
      - .env
  actions:
    image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:actions"
    platform: linux/amd64
    volumes:
      - ${WEBAPP_STORAGE_HOME}/shared-data:/action-server/actions/actions_plugins/recipe-server/images
  #init:
  #  image: dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:init
  #  volumes:
  #    - ${WEBAPP_STORAGE_HOME}/shared-data:/data
  #  command: sh -c 'chown -R 1000:1000 /data && chmod -R 775 /data'
  #  user: "root"
  #  depends_on:
  #    - actions
  nginx:
    image: dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:nginx
    volumes:
      - ${WEBAPP_STORAGE_HOME}/shared-data:/usr/share/nginx/html
    restart: always
  #code-interpretor:
  #  image: dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:code-interpreter
  #  #command: 'python3 -c "import localserver.main; localserver.main.start()"'