version: "3.4"


#version: "3.4"

services:
  server:
     platform: linux/amd64
     container_name: recipes-ai-server
     image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:server"
     volumes:
       - shared-data:/app/recipes/public
 
  chat:
     platform: linux/amd64
     container_name: recipes-ai-chat
     image: "dkdsprototypesreg01.azurecr.io/humanitarian-ai-assistant:chat"
     ports:
       - 80:8000
     volumes:
       - shared-data:/app/public/images

volumes:
  pgdata2:
  shared-data:

