openapi: 3.0.2
info:
  title: Sema4.ai Action Server
  version: 0.1.0
servers:
- url: http://actions:8080
paths:
  
  /api/actions/get-data-recipe-memory/get-memory/run:
    post:
      summary: Get Memory
      description: Performs a search in the memory for a given intent and returns
        the best match found.
      operationId: get_memory_recipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_input:
                  type: string
                  description: The user input text
                chat_history:
                  type: string
                  description: The chat history text
                generate_intent:
                  type: string
                  description: Flag to indicate if intent should be generated
                  enum:
                    - "true"
                    - "false"
                  #default: "true"
              required:
                - user_input
                - chat_history
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                title: Response Get Memory
                description: The 3 best matches found in the memory.
                properties:
                  attribution:
                    type: string
                    description: Attribution information
        "422":
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-openai-isConsequential: false
components:
  schemas:
    HTTPValidationError:
      title: HTTPValidationError
      properties:
        errors:
          title: Errors
          items:
            $ref: '#/components/schemas/ValidationError'
    ValidationError:
      title: ValidationError
      required:
      - loc
      - msg
      - type
      properties:
        loc:
          title: Location
          items:
            anyOf:
            - {}
            - {}
        msg:
          title: Message
        type:
          title: Error Type